# Generated by Django 5.2.1 on 2025-05-10 13:17

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                name="unique_lower_title",
            ),
        ),
    ]
